set_property PACKAGE_PIN W7 [get_ports {Q1[6]}]
set_property PACKAGE_PIN W6 [get_ports {Q1[5]}]
set_property PACKAGE_PIN U8 [get_ports {Q1[4]}]
set_property PACKAGE_PIN V8 [get_ports {Q1[3]}]
set_property PACKAGE_PIN U5 [get_ports {Q1[2]}]
set_property PACKAGE_PIN V5 [get_ports {Q1[1]}]
set_property PACKAGE_PIN U7 [get_ports {Q1[0]}]
set_property PACKAGE_PIN V19 [get_ports {Q[3]}]
set_property PACKAGE_PIN U19 [get_ports {Q[2]}]
set_property PACKAGE_PIN E19 [get_ports {Q[1]}]
set_property PACKAGE_PIN U16 [get_ports {Q[0]}]

set_property PACKAGE_PIN W19 [get_ports clk]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports up]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]


