set_property IOSTANDARD LVCMOS33 [get_ports {number[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports anode1]
set_property IOSTANDARD LVCMOS33 [get_ports anode2]
set_property IOSTANDARD LVCMOS33 [get_ports anode3]
set_property IOSTANDARD LVCMOS33 [get_ports anode4]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports equal]
set_property IOSTANDARD LVCMOS33 [get_ports overflow]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W17 [get_ports {number[3]}]
set_property PACKAGE_PIN V17 [get_ports {number[0]}]
set_property PACKAGE_PIN W16 [get_ports {number[2]}]
set_property PACKAGE_PIN V16 [get_ports {number[1]}]
set_property PACKAGE_PIN W4 [get_ports anode1]
set_property PACKAGE_PIN U4 [get_ports anode3]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports equal]
set_property PACKAGE_PIN U16 [get_ports overflow]
set_property PACKAGE_PIN T17 [get_ports rst]
set_property PACKAGE_PIN W7 [get_ports {O[6]}]
set_property PACKAGE_PIN W6 [get_ports {O[5]}]
set_property PACKAGE_PIN U8 [get_ports {O[4]}]
set_property PACKAGE_PIN V8 [get_ports {O[3]}]
set_property PACKAGE_PIN U5 [get_ports {O[2]}]
set_property PACKAGE_PIN V5 [get_ports {O[1]}]
set_property PACKAGE_PIN U7 [get_ports {O[0]}]

set_property PACKAGE_PIN V4 [get_ports anode2]
set_property PACKAGE_PIN U2 [get_ports anode4]

set_property PACKAGE_PIN T18 [get_ports to_start]
set_property IOSTANDARD LVCMOS33 [get_ports to_start]


set_property PACKAGE_PIN L1 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports add]

set_property IOSTANDARD LVCMOS33 [get_ports roller]
set_property PACKAGE_PIN P1 [get_ports roller]

set_property IOSTANDARD LVCMOS33 [get_ports endroll]
set_property PACKAGE_PIN N3 [get_ports endroll]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN P3 [get_ports reset]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets equal_IBUF]
